@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'Sdk4me.GraphQL.PowerShell.dll'

    # Version number of this module.
    ModuleVersion = '1.4.2'

    # ID used to uniquely identify this module
    GUID = '3443686b-7b29-46dc-8798-aa15883f2864'
    
    # Author of this module
    Author = '4me Inc.'

    # Company or vendor of this module
    CompanyName = '4me Inc.'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2024 4me Inc.'

    # Description of the functionality provided by this module
    Description = 'This PowerShell module provides an easy and efficient way to interact with the 4me GraphQL API. The module leverages the Sdk4me.GraphQL library to simplify the process of interacting with the 4me GraphQL API, allowing you to take full advantage of its query and mutation capabilities.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Supported editions of PowerShell
    CompatiblePSEditions = @('Desktop', 'Core')

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @(
        'Sdk4me.GraphQL.PowerShell.dll',
        'Microsoft.Bcl.HashCode.dll',
        'Newtonsoft.Json.dll',
        'System.Buffers.dll',
        'System.Collections.Immutable.dll',
        'System.Memory.dll',
        'System.Numerics.Vectors.dll',
        'System.Runtime.CompilerServices.Unsafe.dll'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @(
        'Invoke-AccountQuery',
        'New-AccountQuery',
        'New-ActivityIDQuery',
        'New-AddressQuery',
        'Invoke-AffectedSlaQuery',
        'New-AffectedSlaQuery',
        'New-AffectedSlaQueryFilter',
        'New-AgileBoard',
        'Set-AgileBoard',
        'New-AgileBoardColumnQuery',
        'New-AgileBoardItemQuery',
        'Invoke-AgileBoardQuery',
        'New-AgileBoardQuery',
        'New-AgileBoardQueryFilter',
        'New-AppInstance',
        'Set-AppInstance',
        'Invoke-AppInstanceQuery',
        'New-AppInstanceQuery',
        'New-AppInstanceQueryFilter',
        'New-AppOffering',
        'Set-AppOffering',
        'New-AppOfferingAutomationRule',
        'Remove-AppOfferingAutomationRule',
        'Set-AppOfferingAutomationRule',
        'New-AppOfferingAutomationRuleQuery',
        'Invoke-AppOfferingQuery',
        'New-AppOfferingQuery',
        'New-AppOfferingQueryFilter',
        'New-AppOfferingScopeQuery',
        'Invoke-ArchiveQuery',
        'New-ArchiveQuery',
        'New-ArchiveQueryFilter',
        'New-AsyncQueryQuery',
        'New-Attachment',
        'Send-Attachment',
        'New-AttachmentQuery',
        'Invoke-AttachmentStorageQuery',
        'New-AttachmentStorageQuery',
        'New-AttachmentStorageQueryFilter',
        'New-AutomationRule',
        'Set-AutomationRule',
        'New-AutomationRuleActionQuery',
        'New-AutomationRuleExpressionQuery',
        'Invoke-AutomationRuleQuery',
        'New-AutomationRuleQuery',
        'New-AutomationRuleQueryFilter',
        'New-Broadcast',
        'Set-Broadcast',
        'Invoke-BroadcastQuery',
        'New-BroadcastQuery',
        'New-BroadcastQueryFilter',
        'New-BroadcastTranslationQuery',
        'New-Calendar',
        'Set-Calendar',
        'New-CalendarHourQuery',
        'Invoke-CalendarQuery',
        'New-CalendarQuery',
        'New-CalendarQueryFilter',
        'New-ConfigurationItem',
        'Set-ConfigurationItem',
        'Invoke-ConfigurationItemQuery',
        'New-ConfigurationItemQuery',
        'New-ConfigurationItemQueryFilter',
        'New-ConfigurationItemRelationQuery',
        'New-Connection',
        'New-ContactQuery',
        'New-Contract',
        'Set-Contract',
        'Invoke-ContractQuery',
        'New-ContractQuery',
        'New-ContractQueryFilter',
        'New-CustomCollection',
        'Set-CustomCollection',
        'New-CustomCollectionElement',
        'Set-CustomCollectionElement',
        'Invoke-CustomCollectionElementQuery',
        'New-CustomCollectionElementQuery',
        'New-CustomCollectionElementQueryFilter',
        'Invoke-CustomCollectionQuery',
        'New-CustomCollectionQuery',
        'New-CustomCollectionQueryFilter',
        'Add-CustomField',
        'New-CustomFieldCollection',
        'New-CustomFieldQuery',
        'Show-CustomFields',
        'New-CustomFilter',
        'Save-DataExport',
        'Start-DataExport',
        'Start-DataImport',
        'Wait-DataImport',
        'New-EffortClass',
        'Set-EffortClass',
        'Invoke-EffortClassQuery',
        'New-EffortClassQuery',
        'New-EffortClassQueryFilter',
        'New-EffortClassRateIDQuery',
        'New-EffortClassRateQuery',
        'New-EmailTemplateQuery',
        'New-Event',
        'New-FeedbackQuery',
        'New-FeedbackUrlsQuery',
        'New-FirstLineSupportAgreement',
        'Set-FirstLineSupportAgreement',
        'Invoke-FirstLineSupportAgreementQuery',
        'New-FirstLineSupportAgreementQuery',
        'New-FirstLineSupportAgreementQueryFilter',
        'New-Holiday',
        'Set-Holiday',
        'Invoke-HolidayQuery',
        'New-HolidayQuery',
        'New-HolidayQueryFilter',
        'New-InboundEmailQuery',
        'New-Invoice',
        'Set-Invoice',
        'Invoke-InvoiceQuery',
        'New-InvoiceQuery',
        'New-InvoiceQueryFilter',
        'New-KnowledgeArticle',
        'Set-KnowledgeArticle',
        'Invoke-KnowledgeArticleQuery',
        'New-KnowledgeArticleQuery',
        'New-KnowledgeArticleQueryFilter',
        'Invoke-KnowledgeArticleTemplateQuery',
        'New-KnowledgeArticleTemplateQuery',
        'New-KnowledgeArticleTemplateQueryFilter',
        'Invoke-MeQuery',
        'New-MeQuery',
        'New-Note',
        'New-NoteQuery',
        'New-NoteReaction',
        'Remove-NoteReaction',
        'New-NoteReactionQuery',
        'New-Organization',
        'Set-Organization',
        'Invoke-OrganizationQuery',
        'New-OrganizationQuery',
        'New-OrganizationQueryFilter',
        'New-OutOfOfficePeriod',
        'Set-OutOfOfficePeriod',
        'Invoke-OutOfOfficePeriodQuery',
        'New-OutOfOfficePeriodQuery',
        'New-OutOfOfficePeriodQueryFilter',
        'New-ParentServiceInstanceQuery',
        'New-PdfDesign',
        'Set-PdfDesign',
        'Invoke-PdfDesignQuery',
        'New-PdfDesignQuery',
        'New-PdfDesignQueryFilter',
        'New-PeriodQuery',
        'New-PermissionQuery',
        'New-Person',
        'Set-Person',
        'Invoke-PersonQuery',
        'New-PersonQuery',
        'New-PersonQueryFilter',
        'New-Problem',
        'Set-Problem',
        'Invoke-ProblemQuery',
        'New-ProblemQuery',
        'New-ProblemQueryFilter',
        'New-Product',
        'Set-Product',
        'New-ProductBacklog',
        'Set-ProductBacklog',
        'New-ProductBacklogItemQuery',
        'Invoke-ProductBacklogQuery',
        'New-ProductBacklogQuery',
        'New-ProductBacklogQueryFilter',
        'New-ProductCategory',
        'Set-ProductCategory',
        'Invoke-ProductCategoryQuery',
        'New-ProductCategoryQuery',
        'New-ProductCategoryQueryFilter',
        'Invoke-ProductQuery',
        'New-ProductQuery',
        'New-ProductQueryFilter',
        'New-Project',
        'Set-Project',
        'New-ProjectCategory',
        'Set-ProjectCategory',
        'Invoke-ProjectCategoryQuery',
        'New-ProjectCategoryQuery',
        'New-ProjectCategoryQueryFilter',
        'New-ProjectPhaseQuery',
        'Invoke-ProjectQuery',
        'New-ProjectQuery',
        'New-ProjectQueryFilter',
        'New-ProjectRiskLevel',
        'Set-ProjectRiskLevel',
        'Invoke-ProjectRiskLevelQuery',
        'New-ProjectRiskLevelQuery',
        'New-ProjectRiskLevelQueryFilter',
        'New-ProjectTask',
        'Set-ProjectTask',
        'New-ProjectTaskAssignmentQuery',
        'Invoke-ProjectTaskQuery',
        'New-ProjectTaskQuery',
        'New-ProjectTaskQueryFilter',
        'New-ProjectTaskTemplate',
        'Set-ProjectTaskTemplate',
        'New-ProjectTaskTemplateAssignmentQuery',
        'Invoke-ProjectTaskTemplateQuery',
        'New-ProjectTaskTemplateQuery',
        'New-ProjectTaskTemplateQueryFilter',
        'New-ProjectTaskTemplateRelationQuery',
        'New-ProjectTemplate',
        'Set-ProjectTemplate',
        'New-ProjectTemplatePhaseQuery',
        'Invoke-ProjectTemplateQuery',
        'New-ProjectTemplateQuery',
        'New-ProjectTemplateQueryFilter',
        'New-ProviderShopArticleQuery',
        'New-ProviderShopOrderLineQuery',
        'Invoke-RateLimitQuery',
        'New-RateLimitQuery',
        'New-RecordQuery',
        'New-RecurrenceQuery',
        'New-RecurrenceTemplateQuery',
        'New-Release',
        'Set-Release',
        'Invoke-ReleaseQuery',
        'New-ReleaseQuery',
        'New-ReleaseQueryFilter',
        'New-Request',
        'Set-Request',
        'Invoke-RequestQuery',
        'New-RequestQuery',
        'New-RequestQueryFilter',
        'New-RequestTemplate',
        'Set-RequestTemplate',
        'Invoke-RequestTemplateQuery',
        'New-RequestTemplateQuery',
        'New-RequestTemplateQueryFilter',
        'New-Reservation',
        'Set-Reservation',
        'New-ReservationOffering',
        'Set-ReservationOffering',
        'Invoke-ReservationOfferingQuery',
        'New-ReservationOfferingQuery',
        'New-ReservationOfferingQueryFilter',
        'Invoke-ReservationQuery',
        'New-ReservationQuery',
        'New-ReservationQueryFilter',
        'New-Risk',
        'Set-Risk',
        'Invoke-RiskQuery',
        'New-RiskQuery',
        'New-RiskQueryFilter',
        'New-RiskSeverity',
        'Set-RiskSeverity',
        'Invoke-RiskSeverityQuery',
        'New-RiskSeverityQuery',
        'New-RiskSeverityQueryFilter',
        'New-ScrumWorkspace',
        'Set-ScrumWorkspace',
        'Invoke-ScrumWorkspaceQuery',
        'New-ScrumWorkspaceQuery',
        'New-ScrumWorkspaceQueryFilter',
        'New-Service',
        'Set-Service',
        'New-ServiceCategory',
        'Set-ServiceCategory',
        'Invoke-ServiceCategoryQuery',
        'New-ServiceCategoryQuery',
        'New-ServiceCategoryQueryFilter',
        'New-ServiceInstance',
        'Set-ServiceInstance',
        'Invoke-ServiceInstanceQuery',
        'New-ServiceInstanceQuery',
        'New-ServiceInstanceQueryFilter',
        'New-ServiceLevelAgreement',
        'Set-ServiceLevelAgreement',
        'Invoke-ServiceLevelAgreementQuery',
        'New-ServiceLevelAgreementQuery',
        'New-ServiceLevelAgreementQueryFilter',
        'New-ServiceOffering',
        'Set-ServiceOffering',
        'Invoke-ServiceOfferingQuery',
        'New-ServiceOfferingQuery',
        'New-ServiceOfferingQueryFilter',
        'Invoke-ServiceQuery',
        'New-ServiceQuery',
        'New-ServiceQueryFilter',
        'New-ShopArticle',
        'Set-ShopArticle',
        'New-ShopArticleCategory',
        'Set-ShopArticleCategory',
        'Invoke-ShopArticleCategoryQuery',
        'New-ShopArticleCategoryQuery',
        'New-ShopArticleCategoryQueryFilter',
        'Invoke-ShopArticleQuery',
        'New-ShopArticleQuery',
        'New-ShopArticleQueryFilter',
        'New-ShopOrderLine',
        'Set-ShopOrderLine',
        'Invoke-ShopOrderLineQuery',
        'New-ShopOrderLineQuery',
        'New-ShopOrderLineQueryFilter',
        'New-ShortUrl',
        'Set-ShortUrl',
        'Invoke-ShortUrlQuery',
        'New-ShortUrlQuery',
        'New-ShortUrlQueryFilter',
        'New-Site',
        'Set-Site',
        'Invoke-SiteQuery',
        'New-SiteQuery',
        'New-SiteQueryFilter',
        'New-SkillPool',
        'Set-SkillPool',
        'Invoke-SkillPoolQuery',
        'New-SkillPoolQuery',
        'New-SkillPoolQueryFilter',
        'New-SlaCoverageGroup',
        'Set-SlaCoverageGroup',
        'New-SlaCoverageGroupQuery',
        'New-SlaNotificationRuleQuery',
        'New-SlaNotificationScheme',
        'Set-SlaNotificationScheme',
        'Invoke-SlaNotificationSchemeQuery',
        'New-SlaNotificationSchemeQuery',
        'New-SlaNotificationSchemeQueryFilter',
        'New-SnapshotQuery',
        'New-Sprint',
        'Set-Sprint',
        'New-SprintBacklogItemQuery',
        'Invoke-SprintQuery',
        'New-SprintQuery',
        'New-SprintQueryFilter',
        'New-StandardServiceRequestActivityIDQuery',
        'New-StandardServiceRequestQuery',
        'New-Survey',
        'Set-Survey',
        'New-SurveyAnswerQuery',
        'Invoke-SurveyQuery',
        'New-SurveyQuery',
        'New-SurveyQueryFilter',
        'New-SurveyQuestionQuery',
        'New-SurveyResponse',
        'Set-SurveyResponse',
        'Invoke-SurveyResponseQuery',
        'New-SurveyResponseQuery',
        'New-SurveyResponseQueryFilter',
        'Invoke-SyncSetQuery',
        'New-SyncSetQuery',
        'New-SyncSetQueryFilter',
        'New-TagQuery',
        'New-Task',
        'Set-Task',
        'New-TaskApprovalQuery',
        'Invoke-TaskQuery',
        'New-TaskQuery',
        'New-TaskQueryFilter',
        'New-TaskTemplate',
        'Set-TaskTemplate',
        'New-TaskTemplateApprovalQuery',
        'Invoke-TaskTemplateQuery',
        'New-TaskTemplateQuery',
        'New-TaskTemplateQueryFilter',
        'New-Team',
        'Set-Team',
        'Invoke-TeamQuery',
        'New-TeamQuery',
        'New-TeamQueryFilter',
        'New-TimeAllocation',
        'Set-TimeAllocation',
        'Invoke-TimeAllocationQuery',
        'New-TimeAllocationQuery',
        'New-TimeAllocationQueryFilter',
        'New-TimeEntry',
        'Set-TimeEntry',
        'Invoke-TimeEntryQuery',
        'New-TimeEntryQuery',
        'New-TimeEntryQueryFilter',
        'New-TimesheetSetting',
        'Set-TimesheetSetting',
        'Invoke-TimesheetSettingQuery',
        'New-TimesheetSettingQuery',
        'New-TimesheetSettingQueryFilter',
        'New-Translation',
        'Set-Translation',
        'Invoke-TranslationQuery',
        'New-TranslationQuery',
        'New-TranslationQueryFilter',
        'Invoke-TrashQuery',
        'New-TrashQuery',
        'New-TrashQueryFilter',
        'New-UiExtension',
        'Set-UiExtension',
        'Invoke-UiExtensionQuery',
        'New-UiExtensionQuery',
        'New-UiExtensionQueryFilter',
        'New-UiExtensionVersionQuery',
        'New-WaitingForCustomerFollowUp',
        'Set-WaitingForCustomerFollowUp',
        'Invoke-WaitingForCustomerFollowUpQuery',
        'New-WaitingForCustomerFollowUpQuery',
        'New-WaitingForCustomerFollowUpQueryFilter',
        'New-WaitingForCustomerRuleQuery',
        'New-WatchQuery',
        'New-Webhook',
        'Remove-Webhook',
        'Set-Webhook',
        'New-WebhookPolicy',
        'Remove-WebhookPolicy',
        'Set-WebhookPolicy',
        'New-WebhookPolicyCreateResponseQuery',
        'Invoke-WebhookPolicyQuery',
        'New-WebhookPolicyQuery',
        'New-WebhookPolicyQueryFilter',
        'Invoke-WebhookQuery',
        'New-WebhookQuery',
        'New-WebhookQueryFilter',
        'New-Workflow',
        'Set-Workflow',
        'New-WorkflowPhaseQuery',
        'Invoke-WorkflowQuery',
        'New-WorkflowQuery',
        'New-WorkflowQueryFilter',
        'New-WorkflowTaskTemplateRelationQuery',
        'New-WorkflowTemplate',
        'Set-WorkflowTemplate',
        'New-WorkflowTemplatePhaseQuery',
        'Invoke-WorkflowTemplateQuery',
        'New-WorkflowTemplateQuery',
        'New-WorkflowTemplateQueryFilter',
        'New-WorkflowType',
        'Set-WorkflowType',
        'Invoke-WorkflowTypeQuery',
        'New-WorkflowTypeQuery',
        'New-WorkflowTypeQueryFilter'
    )
   
    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('4me', 'Sdk4me', 'GraphQL')

            # A URL to the license for this module.
            LicenseUri = 'https://opensource.org/licenses/MIT'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/code4me/4me-sdk-graphql-powershell'

            # A URL to an icon representing this module.
            # IconUri = ''
        }   
    }
    
    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/code4me/4me-sdk-graphql-powershell/README.md'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = '4me'
}
